// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Securit.Persistence.EF;

namespace Securit.Persistence.EF.Migrations
{
    [DbContext(typeof(SecurityContext))]
    partial class SecurityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectAction", b =>
                {
                    b.Property<int>("ProjectActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectActionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectControllerID")
                        .HasColumnType("int");

                    b.HasKey("ProjectActionID");

                    b.HasIndex("ProjectControllerID");

                    b.ToTable("ProjectActions");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectArea", b =>
                {
                    b.Property<int>("ProjectAreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectAreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectAreaID");

                    b.ToTable("ProjectAreas");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectController", b =>
                {
                    b.Property<int>("ProjectControllerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProjectAreaID")
                        .HasColumnType("int");

                    b.Property<string>("ProjectControllerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectControllerID");

                    b.HasIndex("ProjectAreaID");

                    b.ToTable("ProjectControllers");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.RoleAction", b =>
                {
                    b.Property<int>("RoleActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HasPermission")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectActionID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("RoleActionID");

                    b.HasIndex("ProjectActionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleActions");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectAction", b =>
                {
                    b.HasOne("Security.Domain.Model.Models.ProjectController", "ProjectController")
                        .WithMany("ProjectActions")
                        .HasForeignKey("ProjectControllerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectController");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectController", b =>
                {
                    b.HasOne("Security.Domain.Model.Models.ProjectArea", "ProjectArea")
                        .WithMany("ProjectControllers")
                        .HasForeignKey("ProjectAreaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectArea");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.RoleAction", b =>
                {
                    b.HasOne("Security.Domain.Model.Models.ProjectAction", "ProjectAction")
                        .WithMany("RoleActions")
                        .HasForeignKey("ProjectActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Security.Domain.Model.Models.Role", "Role")
                        .WithMany("RoleActions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectAction");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.User", b =>
                {
                    b.HasOne("Security.Domain.Model.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectAction", b =>
                {
                    b.Navigation("RoleActions");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectArea", b =>
                {
                    b.Navigation("ProjectControllers");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.ProjectController", b =>
                {
                    b.Navigation("ProjectActions");
                });

            modelBuilder.Entity("Security.Domain.Model.Models.Role", b =>
                {
                    b.Navigation("RoleActions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
